version: '3.8'

services:

  db_veiculos:
    image: postgres:15-alpine
    container_name: db_veiculos
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: frota_veiculos
    ports:
      - "5432:5432"
    volumes:
      - veiculos_data:/var/lib/postgresql/data

  micro_veiculos:
    build:
      context: .
      dockerfile: veiculos/Dockerfile
    container_name: micro_veiculos
    restart: on-failure
    ports:
      - "50051:50051"
    depends_on:
      - db_veiculos
    environment:
      DB_HOST: db_veiculos
      DB_NAME: frota_veiculos
      DB_USER: admin
      DB_PASSWORD: admin

  db_manutencoes:
    image: postgres:14-alpine
    container_name: db_manutencoes
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: frota_db_manutencoes
    ports:
      - "5433:5432"

  micro_manutencoes:
    build:
      context: .
      dockerfile: ./manutencoes/Dockerfile
    container_name: micro_manutencoes
    restart: always
    environment:
      MANUTENCOES_DB_HOST: db_manutencoes
      MANUTENCOES_DB_NAME: frota_db_manutencoes
      MANUTENCOES_DB_USER: admin
      MANUTENCOES_DB_PASSWORD: admin

      VEICULOS_HOST: micro_veiculos:50051
    ports:
      - "50052:50052"
    depends_on:
      - db_manutencoes
      - micro_veiculos
    volumes:
      - ./manutencoes/src:/app
      - ./proto:/app/proto

volumes:
  veiculos_data:

    